import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Providers } from "./Providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import FullPageLoader from "@/components/ui/FullPageLoader";
import ClientOnlyWrapper from "@/components/ClientOnlyWrapper";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-Inter",
});

export const metadata: Metadata = {
  title: "TimeFlyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <link rel="preload" as="image" href="/img/heroSlide1.webp" fetchPriority="high"></link>
      <link rel="preload" as="image" href="/img/heroSlide2.webp" fetchPriority="high"></link>
      <link rel="preload" as="image" href="/img/heroSlide3.webp" fetchPriority="high"></link>
      <link rel="preload" as="image" href="/img/heroSlide4.webp" fetchPriority="high"></link>
      <link rel="preload" as="image" href="/img/heroSlide5.webp" fetchPriority="high"></link>
      <body className="antialiased">
        <ToastContainer position="top-right" autoClose={3000} />
        <Providers>
          <Suspense>
            <ClientOnlyWrapper>
              <FullPageLoader />
            </ClientOnlyWrapper>
            {children}
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
